version: '3.9'

services:
  database:
    image: postgres
    container_name: test_fin_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app_fin_api
    restart: always
    ports:
      - 3335:3333
      - 9999:9999
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
